services:
  mongodb:
    image: mongo:latest
    container_name: nest_monorepo_mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:latest
    container_name: nest_monorepo_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analytics_db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: test_assignment_redis
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data

  data-processor:
    build:
      context: ./backend
      dockerfile: Dockerfile.data-processor
    container_name: nest_data_processor
    ports:
      - '3000:3000'
    environment:
      - MONGO_HOST=mongodb
      - REDIS_HOST=redis
    depends_on:
      - mongodb
      - redis

  analytics-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.analytics-service
    container_name: nest_analytics_service
    ports:
      - '3001:3001'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=analytics_db
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb
    depends_on:
      - postgres
      - redis
      - mongodb

volumes:
  mongo_data:
  pg_data:
  redis_data:
